[project]
name = 'decentralized-treasury-management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance-reporting]
path = 'contracts/compliance-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.investment-policy]
path = 'contracts/investment-policy.clar'
clarity_version = 2
epoch = 2.5

[contracts.treasury-core]
path = 'contracts/treasury-core.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
